
[energy]
	#Whether to consume energy when performing a scan. Will make the scanner a chargeable item.
	useEnergy = true
	#Amount of energy used by the common ore module per scan.
	#Range: > 0
	energyCostModuleOreCommon = 2500
	#Amount of energy used by the animal module per scan.
	#Range: > 0
	energyCostModuleAnimal = 500
	#Amount of energy used by the fluid module per scan.
	#Range: > 0
	energyCostModuleFluid = 1000
	#Amount of energy used by the monster module per scan.
	#Range: > 0
	energyCostModuleMonster = 1000
	#Amount of energy used by the block module per scan.
	#Range: > 0
	energyCostModuleBlock = 2500
	#Amount of energy that can be stored in a scanner.
	#Range: > 0
	energyCapacityScanner = 50000
	#Amount of energy used by the range module per scan.
	#Range: > 0
	energyCostModuleRange = 2500
	#Amount of energy used by the structure module per scan.
	#Range: > 0
	energyCostModuleStructure = 5000
	#Amount of energy used by the entity module per scan.
	#Range: > 0
	energyCostModuleEntity = 1500
	#Amount of energy used by the rare ore module per scan.
	#Range: > 0
	energyCostModuleOreRare = 10000

[general]
	#How long the results from a scan should remain visible, in milliseconds.
	#Range: 1000 ~ 300000
	scanStayDuration = 10000
	#The basic scan radius without range modules. Higher values mean more computational
	#overhead and thus potentially worse performance while scanning.
	#IMPORTANT: some modules such as the block and ore scanner modules will already use
	#a reduced radius based on this value. Specifically, the ore scanners multiply this
	#value by 0.25, and the block scanner multiplies it by 0.5.
	#Range modules will boost the range by half this value.
	#Range: 16 ~ 128
	baseScanRadius = 64

[blocks]
	#Registry names of blocks that should be ignored.
	#Blocks in this list will be excluded from the default ore list based on the forge:ores
	#tag and it will be impossible to tune the entity module to this block.
	ignoredBlocks = ["minecraft:command_block"]
	#Tag names of block tags that should be ignored.
	#Blocks matching a tag in this list will be excluded from the default ore list based on theforge:ores tag and it will be impossible to tune the entity module to this block.
	ignoredBlockTags = []

[ores]
	#Registry names of blocks considered 'common ores', requiring the common ore scanner module.
	commonOreBlocks = []
	#Block tags of blocks considered 'rare ores', requiring the common ore scanner module.
	#Any block with the forge:ores tag is implicitly in this list, unless the block also
	#matches an ignored or common ore block tag, or is an ignored or common block.
	rareOreBlockTags = []
	#Block tags of blocks considered 'common ores', requiring the common ore scanner module.
	commonOreBlockTags = ["forge:ores/iron", "forge:ores/redstone", "forge:ores/coal", "forge:ores/quartz", "forge:ores/certus_quartz" "forge:ores/aluminum", "forge:ores/osmium", "forge:ores/fluorite", "forge:ores/niter", "forge:ores/sulfur", "forge:ores/copper", "forge:ores/tin", "forge:ores/lead", "forge:ores/nickel"]
	#Registry names of blocks considered 'rare ores', requiring the common ore scanner module.
	rareOreBlocks = ["minecraft:glowstone", "appliedenergistics2:charged_quartz_ore"]

[fluids]
	#Fluid tags of fluids that should be ignored.
	ignoredFluidTags = []

[structures]
	#The list of structures the structure module scans for.
	structures = []

